//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carCore_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int id { get; set; }
        public Nullable<int> make { get; set; }
        public Nullable<int> model { get; set; }
        public int year { get; set; }
        public string color { get; set; }
        public int mileage { get; set; }
        public decimal price { get; set; }
        public string description { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Model Model1 { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Image> Images { get; set; }
    }
}
