//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carCore_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_data
    {
        public int car_id { get; set; }
        public string car_name { get; set; }
        public int car_price { get; set; }
        public string car_description { get; set; }
        public string car_img { get; set; }
    }
}
