//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carCore_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class rent
    {
        public string Name { get; set; }
        public int Year { get; set; }
        public int People { get; set; }
        public string Tank { get; set; }
        public string Speedometer { get; set; }
        public string Type { get; set; }
        public string Price { get; set; }
        public string img { get; set; }
    }
}
